apiVersion: v1
kind: ServiceAccount
metadata:
  name: devenv-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devenv-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devenv-operator-manager-role
subjects:
- kind: ServiceAccount
  name: devenv-manager
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devenv-api-deployment
  labels:
    app: devenv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devenv-api
  template:
    metadata:
      labels:
        app: devenv-api
    spec:
      containers:
      - name: devenv-api
        image: tmahesh/devenv-api:latest
        #command: ["sleep","infinity"]
      serviceAccountName: devenv-manager
