apiVersion: v1 
kind: Pod 
metadata: 
  name: doll
  labels:
    app.kubernetes.io/name: doll
spec: 
  containers: 
    - name: russian-doll 
      image: tmahesh/russian-doll:latest
      imagePullPolicy: Always 
      securityContext: 
        privileged: true 
      ports:
      - containerPort: 443
        name: https
      # env:
      #   - name: POD_UID
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: metadata.uid 
      volumeMounts: 
        - name: russian-doll-vol
          mountPath: /docker_data 
  volumes: 
    - name: russian-doll-vol
      persistentVolumeClaim:
        claimName: russian-doll-pvc
---
#pvc - for storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: russian-doll-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
#service to expose teh pod

apiVersion: v1
kind: Service
metadata:
  name: doll-service
spec:
  selector:
    app.kubernetes.io/name: doll
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
